global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'th-payment-processor-app1'
    static_configs:
      - targets: ['app1:2112']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'th-payment-processor-app2'
    static_configs:
      - targets: ['app2:2112']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'payment-processor-default'
    static_configs:
      - targets: ['payment-processor-default:2112']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'payment-processor-fallback'
    static_configs:
      - targets: ['payment-processor-fallback:2112']
    scrape_interval: 5s
    metrics_path: '/metrics'